# Site Settings
######################
title: Aaron Alvarez
author: Aaron Alvarez
email: aaronalvarez7394@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software engineer and computer science student studying at the University of Cincinnati.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aaronalvarez.me/" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: aaronisme
github_username: aaron10l
facebook_username: aaron
twitter_username: aaron10l

permalink: /:slug.html

favicon: "./myfavicon.ico" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# Build settings
######################
sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
######################
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "< home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  show_navbar: true # show horizontal navbar in home page
  show_footer: true # show footer links in home page, add in _data/home.yml
  show_education: false # show education history as vertical list, add in _data/home.yml
  show_experiences: true # show experiences as vertical list, add in _data/home.yml
  show_projects: true # show projects as cards, add in _data/home.yml
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_soopr: true # show share buttons using soopr
  soopr_token: "pt_a205cb26449b0d0d5c0fc676cdcd52d0"
  soopr_base_url: "https://sdk.soopr.co"

highlighter: rouge

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk
